#!/bin/bash
DIR="$(dirname "${BASH_SOURCE[0]}")"
WORD=$1
if [ "$WORD" = "" ]; then
	echo Please add a word to search
else
        URL="https://api.dictionaryapi.dev/api/v2/entries/en/$WORD"
        curl -s $URL | $DIR/def-parse.py
fi
